mdss_mdp: fix duplicate declaration derp error
../../../../../../kernel/lge/msm8992/drivers/video/msm/mdss/mdss_mdp.h:555:22: error: duplicate member 'vsync_event_sd'
  struct kernfs_node *vsync_event_sd;

* forgot to remove this line in commit https://github.com/aoleary/G4-Titan-Kernel/commit/b132dae723bab01f46de8f208b948a1a11acb27d